language: python
python:
  - 2.7
env:
#  - PLONE_VERSION=4.1
#  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
#  - PLONE_VERSION=5.0
#matrix:
#  include:
#    - python: 2.6
#      env: PLONE_VERSION=4.0
#    - python: 2.6
#      env: PLONE_VERSION=4.1
#  allow_failures:
#    - python: 2.6
#      env: PLONE_VERSION=4.0
install:
  - python bootstrap.py
  - bin/buildout -t 3
script: bin/test
